### ISSUE TITLE
Make use of earthly to ease development accross engineers

### ISSUE THREAD

**Issue by Tochemey** [chmodas/akka-persistence-r2dbc#108]
We can make use of [earthly](https://docs.earthly.dev/) to ease development among devs.

I will add it to the repo

**Comment by chmodas** [comment]
At the present (and for the foreseeable future), the project requires only a JDK and sbt. While Docker and Compose are highly recommended they are not, strictly speaking, required. You are free to run your own SQL servers if that's what you prefer, as long as you can run the test case. Though I would argue that most developers would have experience with both Docker and Docker Compose, due to their ubiquity, and most likely have them installed.

How would earthly improve the status quo?

**Comment by Tochemey** [comment]
I think you have a point though. Not really a big deal
